/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import boxbuster.Estoque;
import boxbuster.BancoDeDadosFuncionarios;
import boxbuster.Filmes;
import boxbuster.Musicas;
import boxbuster.Produtos;
import boxbuster.Tabuleiros;
import boxbuster.Videogames;
import boxbuster.Gerente;
import boxbuster.Caixa;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author elisrb
 */
public class AreaGerente extends javax.swing.JFrame {
    // variáveis da parte de estoque
    int cont = Estoque.getCont()+1;
    
    private ArrayList<Produtos> allProducts = new ArrayList();
                
    boolean ok = false;
    
    String action = "cancel";
    
    int rowClick = -1;
    int selectedProdInd;
    
    // variáveis da parte de equipe
    BancoDeDadosFuncionarios bdFunc = new BancoDeDadosFuncionarios("funcionarios.txt");
    ArrayList<String> funcionarios = new ArrayList<>();
    int totalFunc = 0;
    ArrayList<String> funcAtual;

    /**
     * Creates new form AreaGerente
     */
    public AreaGerente() {
        setLocationRelativeTo(null);
        
        initComponents();
        
        Estoque.loadEstoque();
        cont = Estoque.getCont()+1;
        
        // inicializa as tabelas
        updateProdList();
        updateFuncionarios(); 
    }

    private void updateProdList() {
        allProducts = Estoque.atualizarLista();
        
        DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Código", "Tipo", "Nome", "Faixa", "Ano", "Preço", "Disp./Alugados"}, 0);

        for(int i = 0; i < allProducts.size(); i++){
            Object linha[] = new Object[]{
            allProducts.get(i).getCodigoProd(),
            allProducts.get(i).getClass().getSimpleName(), 
            allProducts.get(i).getNomeProd(),
            allProducts.get(i).getFaixaEtaria(),
            allProducts.get(i).getAno(),
            allProducts.get(i).getPreco(),
            allProducts.get(i).getDisponiveis() + "/" + allProducts.get(i).getAlugados()};

            tabela.addRow(linha);
        }
        
        tableProdutos.setModel(tabela);        
    }
    
    private void updateFuncionarios() { // atualiza tabela e quantidade de funcionários, e a combo box de gerentes 
        
        // atualiza tabela de funcionarios
        tableEquipe.removeAll();
        funcionarios = bdFunc.lerPessoas(); // retorna uma ArrayList de todos os funcionários
        
        DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Nome", "CPF", "Data de Nascimento", "Código", "Cargo", "Gerente"}, 0);
        String[] palavras;
        
        for(int i = 0; i < funcionarios.size(); i++){
            palavras = funcionarios.get(i).split("_");
            String gerente = "--";
            if(palavras[5].equals("Caixa")){
                gerente = palavras[8]; // caso o funcionário seja gerente preenche o campo "Gerente" da tabela
            }
            Object linha[] = new Object[]{
            palavras[0],
            palavras[1],
            palavras[2],
            palavras[4],
            palavras[5],
            gerente};

            tabela.addRow(linha);
        }
        
        tableEquipe.setModel(tabela);
        
        // atualiza total de caixas e gerentes
        int[] quant = bdFunc.quantidades();
        lblTotalCaixas.setText("Total de caixas: "+ quant[0]);
        lblTotalGerentes.setText("Total de gerentes: "+ quant[1]);
        totalFunc = quant[0]+quant[1];
        
        // atualiza combo box de gerentes
        cmbGerenteEq.removeAllItems();
        cmbGerenteEq.addItem("Selecione");
        
        String[] linha;
        String nomeGerente;
        
        for(int i=0;i<funcionarios.size();i++){
            linha = funcionarios.get(i).split("_");
            if(linha[5].equals("Gerente")){
                nomeGerente = linha[0];
                cmbGerenteEq.addItem(nomeGerente);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGerente = new javax.swing.JPanel();
        tabbedPnlGerente = new javax.swing.JTabbedPane();
        pnlEquipe = new javax.swing.JPanel();
        lblTotalCaixas = new javax.swing.JLabel();
        lblTotalGerentes = new javax.swing.JLabel();
        lblCodigoEq = new javax.swing.JLabel();
        txtfCodigoEq = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtfCPFEq = new javax.swing.JTextField();
        lblTipoEq = new javax.swing.JLabel();
        cmbTipoEq = new javax.swing.JComboBox<>();
        lblNomeEq = new javax.swing.JLabel();
        txtfNomeEq = new javax.swing.JTextField();
        lblDataEq = new javax.swing.JLabel();
        txtfDataEq = new javax.swing.JTextField();
        lblGerente = new javax.swing.JLabel();
        cmbGerenteEq = new javax.swing.JComboBox<>();
        btnVoltarEq = new javax.swing.JButton();
        btnNovoFunc = new javax.swing.JButton();
        btnEditarEq = new javax.swing.JButton();
        btnPesquisarEq = new javax.swing.JButton();
        scrlEquipe = new javax.swing.JScrollPane();
        tableEquipe = new javax.swing.JTable();
        btnConfirmarEq = new javax.swing.JButton();
        btnCancelarEq = new javax.swing.JButton();
        pnlEstoque = new javax.swing.JPanel();
        btnVoltarEst = new javax.swing.JButton();
        btnNovoProd = new javax.swing.JButton();
        btnPesquisarProd = new javax.swing.JButton();
        btnEditarProd = new javax.swing.JButton();
        lblTotalProd = new javax.swing.JLabel();
        lblTipoProd = new javax.swing.JLabel();
        cmbTipoProd = new javax.swing.JComboBox<>();
        lblQuantTipo = new javax.swing.JLabel();
        lblCodigoProd = new javax.swing.JLabel();
        txtfCodigoProd = new javax.swing.JTextField();
        lblFaixaEtaria = new javax.swing.JLabel();
        txtfFaixaEtaria = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtfPreco = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtfNome = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtfAno = new javax.swing.JTextField();
        lblVar1 = new javax.swing.JLabel();
        txtfVar1 = new javax.swing.JTextField();
        lblVar2 = new javax.swing.JLabel();
        txtfVar2 = new javax.swing.JTextField();
        lblVar3 = new javax.swing.JLabel();
        txtfVar3 = new javax.swing.JTextField();
        lblVar4 = new javax.swing.JLabel();
        txtfVar4 = new javax.swing.JTextField();
        btnConfirmarEst = new javax.swing.JButton();
        btnCancelarEst = new javax.swing.JButton();
        scrlProdutos = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        btnEditarProd1 = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        txtfQuantidade = new javax.swing.JTextField();
        menuBarAreaGr = new javax.swing.JMenuBar();
        menuAreaGr = new javax.swing.JMenu();
        menuVoltarAreaGr = new javax.swing.JMenuItem();
        separatorAreaGr = new javax.swing.JPopupMenu.Separator();
        menuSairAreaGr = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do gerente");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogo.png")).getImage());

        pnlGerente.setBorder(javax.swing.BorderFactory.createTitledBorder("Área do Gerente"));

        pnlEquipe.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N

        lblTotalCaixas.setText("Total de caixas: --");

        lblTotalGerentes.setText("Total de gerentes: --");

        lblCodigoEq.setText("Código:");

        txtfCodigoEq.setEnabled(false);
        txtfCodigoEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCodigoEqActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");

        txtfCPFEq.setEnabled(false);
        txtfCPFEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCPFEqActionPerformed(evt);
            }
        });

        lblTipoEq.setText("Tipo:");

        cmbTipoEq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Caixa", "Gerente" }));
        cmbTipoEq.setEnabled(false);

        lblNomeEq.setText("Nome:");

        txtfNomeEq.setEnabled(false);
        txtfNomeEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNomeEqActionPerformed(evt);
            }
        });

        lblDataEq.setText("Data de nasc.:");

        txtfDataEq.setEnabled(false);
        txtfDataEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDataEqActionPerformed(evt);
            }
        });

        lblGerente.setText("Gerente:");

        cmbGerenteEq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cmbGerenteEq.setEnabled(false);

        btnVoltarEq.setText("Voltar");
        btnVoltarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarEqActionPerformed(evt);
            }
        });

        btnNovoFunc.setText("Novo funcionário");
        btnNovoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncActionPerformed(evt);
            }
        });

        btnEditarEq.setText("Editar");
        btnEditarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEqActionPerformed(evt);
            }
        });

        btnPesquisarEq.setText("Pesquisar");
        btnPesquisarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEqActionPerformed(evt);
            }
        });

        tableEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cargo", "Nome", "Data de nasc.", "Pedidos"
            }
        ));
        tableEquipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEquipeMouseClicked(evt);
            }
        });
        scrlEquipe.setViewportView(tableEquipe);

        btnConfirmarEq.setText("Confirmar");
        btnConfirmarEq.setEnabled(false);
        btnConfirmarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEqActionPerformed(evt);
            }
        });

        btnCancelarEq.setText("Cancelar");
        btnCancelarEq.setEnabled(false);
        btnCancelarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEquipeLayout = new javax.swing.GroupLayout(pnlEquipe);
        pnlEquipe.setLayout(pnlEquipeLayout);
        pnlEquipeLayout.setHorizontalGroup(
            pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlEquipe)
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addComponent(btnVoltarEq)
                        .addGap(173, 173, 173)
                        .addComponent(btnConfirmarEq)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlEquipeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoEq)
                            .addComponent(lblNomeEq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfCodigoEq, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfNomeEq, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTotalCaixas))
                .addGap(18, 18, 18)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addComponent(lblTotalGerentes)
                        .addContainerGap(398, Short.MAX_VALUE))
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelarEq)
                            .addGroup(pnlEquipeLayout.createSequentialGroup()
                                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDataEq)
                                    .addComponent(lblCPF))
                                .addGap(18, 18, 18)
                                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfDataEq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfCPFEq, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipeLayout.createSequentialGroup()
                                .addComponent(lblTipoEq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEquipeLayout.createSequentialGroup()
                                .addComponent(lblGerente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGerenteEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77))))
            .addGroup(pnlEquipeLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnNovoFunc)
                .addGap(18, 18, 18)
                .addComponent(btnEditarEq)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarEq)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEquipeLayout.setVerticalGroup(
            pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipeLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoFunc)
                    .addComponent(btnPesquisarEq)
                    .addComponent(btnEditarEq))
                .addGap(31, 31, 31)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCaixas)
                    .addComponent(lblTotalGerentes))
                .addGap(18, 18, 18)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfCodigoEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoEq))
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeEq))
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfCPFEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfDataEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataEq)
                            .addComponent(txtfNomeEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEquipeLayout.createSequentialGroup()
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEq)
                            .addComponent(cmbTipoEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGerente)
                            .addComponent(cmbGerenteEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(pnlEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarEq)
                    .addComponent(btnConfirmarEq)
                    .addComponent(btnCancelarEq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPnlGerente.addTab("Equipe", pnlEquipe);

        btnVoltarEst.setText("Voltar");
        btnVoltarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarEstActionPerformed(evt);
            }
        });

        btnNovoProd.setText("Novo produto");
        btnNovoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdActionPerformed(evt);
            }
        });

        btnPesquisarProd.setText("Pesquisar");
        btnPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdActionPerformed(evt);
            }
        });

        btnEditarProd.setText("Editar");
        btnEditarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdActionPerformed(evt);
            }
        });

        lblTotalProd.setText("Total de produtos: --");

        lblTipoProd.setText("Tipo:");

        cmbTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Filme", "Música", "Tabuleiro", "Videogame" }));
        cmbTipoProd.setEnabled(false);
        cmbTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoProdActionPerformed(evt);
            }
        });

        lblQuantTipo.setText("Produtos desse tipo: --");

        lblCodigoProd.setText("Código:");

        txtfCodigoProd.setEnabled(false);
        txtfCodigoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCodigoProdActionPerformed(evt);
            }
        });

        lblFaixaEtaria.setText("Faixa etária:");

        txtfFaixaEtaria.setEnabled(false);
        txtfFaixaEtaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFaixaEtariaActionPerformed(evt);
            }
        });

        lblPreco.setText("Preço:");

        txtfPreco.setEnabled(false);
        txtfPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPrecoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        txtfNome.setEnabled(false);
        txtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNomeActionPerformed(evt);
            }
        });

        lblAno.setText("Ano:");

        txtfAno.setEnabled(false);
        txtfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAnoActionPerformed(evt);
            }
        });

        lblVar1.setText("----------:");

        txtfVar1.setEnabled(false);
        txtfVar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfVar1ActionPerformed(evt);
            }
        });

        lblVar2.setText("----------:");

        txtfVar2.setEnabled(false);
        txtfVar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfVar2ActionPerformed(evt);
            }
        });

        lblVar3.setText("----------:");

        txtfVar3.setEnabled(false);
        txtfVar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfVar3ActionPerformed(evt);
            }
        });

        lblVar4.setText("----------:");

        txtfVar4.setEnabled(false);
        txtfVar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfVar4ActionPerformed(evt);
            }
        });

        btnConfirmarEst.setText("Confirmar");
        btnConfirmarEst.setEnabled(false);
        btnConfirmarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEstActionPerformed(evt);
            }
        });

        btnCancelarEst.setText("Cancelar");
        btnCancelarEst.setEnabled(false);
        btnCancelarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEstActionPerformed(evt);
            }
        });

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Nome", "Faixa ", "Ano", "Preço", "Disp./Alugados"
            }
        ));
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        scrlProdutos.setViewportView(tableProdutos);

        btnEditarProd1.setText("Excluir");
        btnEditarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProd1ActionPerformed(evt);
            }
        });

        lblQuantidade.setText("Disp./Alugados:");

        txtfQuantidade.setText("/");
        txtfQuantidade.setEnabled(false);
        txtfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEstoqueLayout = new javax.swing.GroupLayout(pnlEstoque);
        pnlEstoque.setLayout(pnlEstoqueLayout);
        pnlEstoqueLayout.setHorizontalGroup(
            pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVar1)
                    .addComponent(lblVar2))
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfVar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstoqueLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtfVar2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlProdutos)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btnConfirmarEst)
                                .addGap(87, 87, 87)
                                .addComponent(btnCancelarEst))
                            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                                .addComponent(btnVoltarEst)
                                .addGap(100, 100, 100)
                                .addComponent(btnNovoProd)
                                .addGap(26, 26, 26)
                                .addComponent(btnPesquisarProd)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarProd)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarProd1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoProd)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTotalProd))
                .addGap(18, 18, 18)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addComponent(lblTipoProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuantTipo)
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlEstoqueLayout.createSequentialGroup()
                                    .addComponent(lblQuantidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlEstoqueLayout.createSequentialGroup()
                                    .addComponent(lblPreco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59))
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFaixaEtaria)
                            .addComponent(lblAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVar3)
                                    .addComponent(lblVar4))
                                .addGap(18, 18, 18)
                                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfVar4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtfVar3))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlEstoqueLayout.setVerticalGroup(
            pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarProd)
                    .addComponent(btnNovoProd)
                    .addComponent(btnVoltarEst)
                    .addComponent(btnEditarProd)
                    .addComponent(btnEditarProd1))
                .addGap(18, 18, 18)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoProd)
                            .addComponent(cmbTipoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalProd))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfCodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodigoProd))
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFaixaEtaria)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblQuantidade))
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAno))
                            .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNome))))
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addComponent(lblQuantTipo)
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco))))
                .addGap(48, 48, 48)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVar1)
                            .addComponent(txtfVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVar2)
                            .addComponent(txtfVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEstoqueLayout.createSequentialGroup()
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVar3)
                            .addComponent(txtfVar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVar4)
                            .addComponent(txtfVar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnlEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarEst, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfirmarEst, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPnlGerente.addTab("Estoque", pnlEstoque);

        javax.swing.GroupLayout pnlGerenteLayout = new javax.swing.GroupLayout(pnlGerente);
        pnlGerente.setLayout(pnlGerenteLayout);
        pnlGerenteLayout.setHorizontalGroup(
            pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabbedPnlGerente, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        pnlGerenteLayout.setVerticalGroup(
            pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(pnlGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGerenteLayout.createSequentialGroup()
                    .addComponent(tabbedPnlGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        menuAreaGr.setText("Menu");

        menuVoltarAreaGr.setText("Voltar");
        menuVoltarAreaGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarAreaGrActionPerformed(evt);
            }
        });
        menuAreaGr.add(menuVoltarAreaGr);
        menuAreaGr.add(separatorAreaGr);

        menuSairAreaGr.setText("Sair");
        menuSairAreaGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairAreaGrActionPerformed(evt);
            }
        });
        menuAreaGr.add(menuSairAreaGr);

        menuBarAreaGr.add(menuAreaGr);

        setJMenuBar(menuBarAreaGr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNomeActionPerformed

    private void txtfCodigoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCodigoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCodigoProdActionPerformed

    private void txtfFaixaEtariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFaixaEtariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFaixaEtariaActionPerformed

    private void txtfPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPrecoActionPerformed

    private void btnNovoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdActionPerformed
        action = "new";
        
        cmbTipoProd.setSelectedItem(cmbTipoProd.getSelectedItem()); //caso o usuário clique no botão após escolher um produto reseta a combo box para os campos específicos ativarem
        
        enableBaseFields();
        txtfCodigoProd.setEnabled(false);
        txtfCodigoProd.setText(Integer.toString(cont));
    }//GEN-LAST:event_btnNovoProdActionPerformed

    private void txtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAnoActionPerformed

    private void menuVoltarAreaGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarAreaGrActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVoltarAreaGrActionPerformed

    private void txtfCPFEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCPFEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCPFEqActionPerformed

    private void txtfDataEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDataEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDataEqActionPerformed

    private void txtfNomeEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNomeEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNomeEqActionPerformed

    private void txtfCodigoEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCodigoEqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCodigoEqActionPerformed

    private void menuSairAreaGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairAreaGrActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairAreaGrActionPerformed

    private void btnVoltarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarEstActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarEstActionPerformed

    private void cmbTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoProdActionPerformed
        String prodType = (String) cmbTipoProd.getSelectedItem();

        btnConfirmarEst.setEnabled(true);

        if (prodType.equals("Filme")){
            lblVar1.setText("Gênero:");
            lblVar2.setText("Estúdio:");
            lblVar3.setText("Diretor:");
            lblVar4.setText("----------:");
            txtfVar1.setEnabled(true);
            txtfVar2.setEnabled(true);
            txtfVar3.setEnabled(true);
            txtfVar4.setEnabled(false);
            txtfVar4.setText("");
        } else if (prodType.equals("Música")){
            lblVar1.setText("Estilo:");
            lblVar2.setText("Autor:");
            lblVar3.setText("----------:");
            lblVar4.setText("----------:");
            txtfVar1.setEnabled(true);
            txtfVar2.setEnabled(true);
            txtfVar3.setEnabled(false);
            txtfVar4.setEnabled(false);
            txtfVar3.setText("");
            txtfVar4.setText("");
        } else if (prodType.equals("Tabuleiro")){
            lblVar1.setText("Tipo:");
            lblVar2.setText("Marca:");
            lblVar3.setText("Nº de jogadores:");
            lblVar4.setText("----------:");
            txtfVar1.setEnabled(true);
            txtfVar2.setEnabled(true);
            txtfVar3.setEnabled(true);
            txtfVar4.setEnabled(false);
            txtfVar4.setText("");
        } else if (prodType.equals("Videogame")){
            lblVar1.setText("Gênero:");
            lblVar2.setText("Desenvolvedor:");
            lblVar3.setText("Nº de jogadores:");
            lblVar4.setText("Plataforma:");
            txtfVar1.setEnabled(true);
            txtfVar2.setEnabled(true);
            txtfVar3.setEnabled(true);
            txtfVar4.setEnabled(true);
        } else {
            lblVar1.setText("----------:");
            lblVar2.setText("----------:");
            lblVar3.setText("----------:");
            lblVar4.setText("----------:");
            txtfVar1.setEnabled(false);
            txtfVar2.setEnabled(false);
            txtfVar3.setEnabled(false);
            txtfVar4.setEnabled(false);

            if(!action.equals("search")){
                btnConfirmarEst.setEnabled(false);
            }
        } 
    }//GEN-LAST:event_cmbTipoProdActionPerformed

    private void txtfVar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfVar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfVar1ActionPerformed

    private void txtfVar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfVar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfVar2ActionPerformed

    private void txtfVar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfVar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfVar3ActionPerformed

    private void txtfVar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfVar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfVar4ActionPerformed

    private void btnConfirmarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEstActionPerformed
        rowClick = -1;
        
        if(action.equals("delete")){
            String prodType = (String) cmbTipoProd.getSelectedItem();
            
            if (prodType.equals("Filme")){
                Estoque.getListaFilmes().remove(selectedProdInd);
            } else if (prodType.equals("Música")){
                Estoque.getListaMusicas().remove(selectedProdInd);
            } else if (prodType.equals("Tabuleiro")){
                Estoque.getListaTabuleiros().remove(selectedProdInd);
            } else if (prodType.equals("Videogame")){
                Estoque.getListaVideogames().remove(selectedProdInd);
            } 
            
            Estoque.reescreverEstoque();
            updateProdList();
            
            clearFields();
            
        } else if(action == "search"){
            tableProdutos.removeAll();
            DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Código", "Tipo", "Nome", "Faixa", "Ano", "Preço", "Alugado"}, 0);

            String disponiveis = "", alugados = "";
            
            String[] quant = txtfQuantidade.getText().split("/");
            
            if(quant.length == 1){
                disponiveis = quant[0];
            } else if (quant.length == 2){
                disponiveis = quant[0];
                alugados = quant[1];
            }
            
            String tipo = (String) cmbTipoProd.getSelectedItem(),
                    codigo = txtfCodigoProd.getText(),
                    faixaEtaria = txtfFaixaEtaria.getText(),
                    preco = txtfPreco.getText(),
                    nome = txtfNome.getText(),
                    ano = txtfAno.getText(),
                    var1 = txtfVar1.getText(),
                    var2 = txtfVar2.getText(),
                    var3 = txtfVar3.getText(),
                    var4 = txtfVar4.getText();
            if(tipo.equals("Selecione")){
                tipo = "";
            }
            for(Produtos prod : allProducts){
                
                String[] info = prod.toString().split("_");
                
                boolean ok3 = true;
                boolean ok4 = true;
                
                if(info.length >= 11 && !info[10].contains(var3)){
                    ok3 = false;
                }
                if(info.length >= 12 && !info[11].contains(var4)){
                    ok4 = false;
                }
                
                if(info[0].contains(tipo) &&
                        info[1].contains(nome) &&
                        info[2].contains(preco) &&
                        info[3].contains(ano) &&
                        info[4].contains(codigo) &&
                        info[5].contains(faixaEtaria) &&
                        info[6].contains(disponiveis) &&
                        info[7].contains(alugados) &&
                        info[8].contains(var1) &&
                        info[9].contains(var2) &&
                        ok3 && ok4){
                    

                    Object linha[] = new Object[]{
                    info[4],
                    info[0]+"s",
                    info[1],
                    info[5],
                    info[3],
                    info[2],
                    info[6] + "/" + info[7]};

                    tabela.addRow(linha);
                    
                }
            }
            tableProdutos.setModel(tabela);
    
        } else if(action.equals("new") || action.equals("edit")) {
            int codigo = Integer.parseInt(txtfCodigoProd.getText());
            String faixaEtaria = txtfFaixaEtaria.getText(),
                    preco = txtfPreco.getText(),
                    nome = txtfNome.getText(),
                    ano = txtfAno.getText();
            
            String[] quant = txtfQuantidade.getText().split("/");
            
            String disponiveis = quant[0];
            String alugados = quant[1];

            String prodType = (String) cmbTipoProd.getSelectedItem();

            ok = true;
            
            try {
                Double.parseDouble(preco);
                Integer.parseInt(ano);
                Integer.parseInt(disponiveis);
                Integer.parseInt(alugados);
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos corretamente.");
                ok = false;
            }
            
            for(Produtos prod : Estoque.getListaProdutos()){
                if(prod.getNomeProd().equals(nome)){
                    JOptionPane.showMessageDialog(null, "Já existe um produto com esse nome.");
                    ok = false;
                }
            }

            if(ok){
                if(faixaEtaria.isEmpty() || preco.isEmpty() || nome.isEmpty() || ano.isEmpty() || quant.length != 2){
                    JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos corretamente.");
                    ok = false;
                } else {
                    if (prodType.equals("Filme")){
                        String genero = txtfVar1.getText(),
                                estudio = txtfVar2.getText(),
                                diretor = txtfVar3.getText();

                        if(genero.isEmpty() || estudio.isEmpty() || diretor.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos.");
                            ok = false;
                        } else {
                            Filmes newFilme = new Filmes(nome, Double.parseDouble(preco), Integer.parseInt(ano), codigo, faixaEtaria, Integer.parseInt(disponiveis), Integer.parseInt(alugados), genero, estudio, diretor);

                            if(action.equals("edit")){
                                Estoque.getListaFilmes().set(selectedProdInd, newFilme);
                            } else if (action.equals("new")){
                                Estoque.addFilme(newFilme);
                                Estoque.salvarProduto(newFilme);
                            }
                        }
                    } else if (prodType.equals("Música")){
                        String estilo = txtfVar1.getText(),
                                autor = txtfVar2.getText();

                        if(estilo.isEmpty() || autor.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos.");
                            ok = false;
                        } else {
                            Musicas newMusica = new Musicas(nome, Double.parseDouble(preco), Integer.parseInt(ano), codigo, faixaEtaria, Integer.parseInt(disponiveis), Integer.parseInt(alugados), estilo, autor);

                            if(action.equals("edit")){
                                Estoque.getListaMusicas().set(selectedProdInd, newMusica);
                            } else if (action.equals("new")){
                                Estoque.addMusica(newMusica);
                                Estoque.salvarProduto(newMusica);;
                            }
                        }
                    } else if (prodType.equals("Tabuleiro")){
                        String tipo = txtfVar1.getText(),
                                marca = txtfVar2.getText(),
                                numJogadores = txtfVar3.getText();

                        if(tipo.isEmpty() || marca.isEmpty() || numJogadores.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos.");
                            ok = false;
                        } else {
                            Tabuleiros newTabuleiro = new Tabuleiros(nome, Double.parseDouble(preco), Integer.parseInt(ano), codigo, faixaEtaria, Integer.parseInt(disponiveis), Integer.parseInt(alugados), numJogadores, tipo, marca);

                            if(action.equals("edit")){
                                Estoque.getListaTabuleiros().set(selectedProdInd, newTabuleiro);
                            } else if (action.equals("new")){
                                Estoque.addTabuleiro(newTabuleiro);
                                Estoque.salvarProduto(newTabuleiro);
                            }
                        }
                    } else if (prodType.equals("Videogame")){
                        String genero = txtfVar1.getText(),
                                estudio = txtfVar2.getText(),
                                numJogadores = txtfVar3.getText(),
                                plataforma = txtfVar4.getText();

                        if(genero.isEmpty() || estudio.isEmpty() || numJogadores.isEmpty() || plataforma.isEmpty()){
                            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos.");
                            ok = false;
                        } else {
                            Videogames newVideogame = new Videogames(nome, Double.parseDouble(preco), Integer.parseInt(ano), codigo, faixaEtaria, Integer.parseInt(disponiveis), Integer.parseInt(alugados), numJogadores, genero, plataforma, estudio);

                            if(action.equals("edit")){
                                Estoque.getListaVideogames().set(selectedProdInd, newVideogame);
                            } else if (action.equals("new")){
                                Estoque.addVideogame(newVideogame);
                                Estoque.salvarProduto(newVideogame);
                            }
                        }
                    }

                    if(ok){
                        cont++;
                        Estoque.setCont(cont);
                        Estoque.reescreverEstoque();

                        updateProdList();

                        disableBaseFields();
                        clearFields();

                        switch(action){
                            case "new":
                                JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso.");
                                break;
                            case "edit":
                                JOptionPane.showMessageDialog(null, "Produto editado com sucesso.");
                                break;
                            case "delete":
                                JOptionPane.showMessageDialog(null, "Produto deletado com sucesso.");
                                break;
                        }
                    }
                }
            }
        }
        
        if(!action.equals("search")){
            action = "confirm";
        }
        cont = Estoque.getCont()+1;
    }//GEN-LAST:event_btnConfirmarEstActionPerformed

    private void btnCancelarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEstActionPerformed
        action = "cancel";
        
        rowClick = -1;
        
        disableBaseFields();
        clearFields();
        
        updateProdList();
    }//GEN-LAST:event_btnCancelarEstActionPerformed

    private void btnPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdActionPerformed
        action = "search";
        
        cmbTipoProd.setSelectedItem(cmbTipoProd.getSelectedItem()); //caso o usuário clique no botão após escolher um produto reseta a combo box para os campos específicos ativarem
        
        if (rowClick >= 0 && rowClick < allProducts.size()){
            Produtos selectedProd = allProducts.get(rowClick);
            
            txtfCodigoProd.setText(Integer.toString(selectedProd.getCodigoProd()));
        } else {
            txtfCodigoProd.setText("");
        }
        
        enableBaseFields();
        btnConfirmarEst.setEnabled(true);
    }//GEN-LAST:event_btnPesquisarProdActionPerformed

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        rowClick = tableProdutos.getSelectedRow();
        
        if (rowClick >= 0 && rowClick < allProducts.size()){
            Produtos selectedProd = allProducts.get(rowClick);
            
            if(!action.equals("new")){
                txtfCodigoProd.setText(Integer.toString(selectedProd.getCodigoProd()));
            } else {
                txtfCodigoProd.setEnabled(false);
            }
            txtfNome.setText(selectedProd.getNomeProd());
            txtfFaixaEtaria.setText(selectedProd.getFaixaEtaria());
            txtfAno.setText(Integer.toString(selectedProd.getAno()));
            txtfPreco.setText(Double.toString(selectedProd.getPreco()));
            txtfQuantidade.setText(selectedProd.getDisponiveis() + "/" + selectedProd.getAlugados());
            
            if(selectedProd.getClass().getSimpleName().equals("Filmes")){
                selectedProdInd = Estoque.getListaFilmes().indexOf(selectedProd);
                
                cmbTipoProd.setSelectedItem("Filme");
                
                txtfVar1.setText(((Filmes) selectedProd).getGenero());
                txtfVar2.setText(((Filmes) selectedProd).getEstudio());
                txtfVar3.setText(((Filmes) selectedProd).getDiretor());
            } else if(selectedProd.getClass().getSimpleName().equals("Musica")){
                selectedProdInd = Estoque.getListaMusicas().indexOf(selectedProd);
                
                cmbTipoProd.setSelectedItem("Música");
                
                txtfVar1.setText(((Musicas) selectedProd).getEstilo());
                txtfVar2.setText(((Musicas) selectedProd).getAutor());
            } else if(selectedProd.getClass().getSimpleName().equals("Tabuleiro")){
                selectedProdInd = Estoque.getListaTabuleiros().indexOf(selectedProd);
                
                cmbTipoProd.setSelectedItem("Tabuleiro");
                
                txtfVar1.setText(((Tabuleiros) selectedProd).getTipo());
                txtfVar2.setText(((Tabuleiros) selectedProd).getMarca());
                txtfVar3.setText(((Tabuleiros) selectedProd).getNumJogadores());
            } else if(selectedProd.getClass().getSimpleName().equals("Videogames")){
                selectedProdInd = Estoque.getListaVideogames().indexOf(selectedProd);
                
                cmbTipoProd.setSelectedItem("Videogame");
                
                txtfVar1.setText(((Videogames) selectedProd).getGenero());
                txtfVar2.setText(((Videogames) selectedProd).getDesenvolvedor());
                txtfVar3.setText(((Videogames) selectedProd).getNumJogadores());
                txtfVar4.setText(((Videogames) selectedProd).getPlataforma());
            }
            if(action.equals("confirm") || action.equals("cancel") || action.equals("delete")){
                disableBaseFields();
            
                txtfVar1.setEnabled(false);
                txtfVar2.setEnabled(false);
                txtfVar3.setEnabled(false);
                txtfVar4.setEnabled(false);
                
                if(!action.equals("delete")){
                    btnConfirmarEst.setEnabled(false);
                }
            } else {
                enableBaseFields();
            }
                        
            btnCancelarEst.setEnabled(true);
        }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void btnEditarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdActionPerformed
        action = "edit";
                
        if (rowClick >= 0 && rowClick < allProducts.size()){
            cmbTipoProd.setSelectedItem(cmbTipoProd.getSelectedItem()); //caso o usuário clique no botão após escolher um produto reseta a combo box para os campos específicos ativarem
            
            Produtos selectedProd = allProducts.get(rowClick);
            
            txtfCodigoProd.setText(Integer.toString(selectedProd.getCodigoProd()));
            
            enableBaseFields();
            
            btnConfirmarEst.setEnabled(true);
        } else {
            txtfCodigoProd.setText("");
            disableBaseFields();
        }
    }//GEN-LAST:event_btnEditarProdActionPerformed

    private void btnVoltarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarEqActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarEqActionPerformed

    private void btnNovoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncActionPerformed
        action = "new";
        enableEquipe();
    }//GEN-LAST:event_btnNovoFuncActionPerformed

    private void btnConfirmarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEqActionPerformed
        if("new".equals(action)){ // cria um novo funcionário
            if(txtfCodigoEq.getText().equals("")|| txtfNomeEq.getText().equals("")|| txtfDataEq.getText().equals("")||
                    txtfCPFEq.getText().equals("")||cmbTipoEq.getSelectedIndex()==0||(cmbTipoEq.getSelectedIndex()==1 && cmbGerenteEq.getSelectedIndex()==0)){
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            }
            else{
                String nome = txtfNomeEq.getText(),
                    cpf = txtfCPFEq.getText(),
                    dataString = txtfDataEq.getText(),
                    codigoString = txtfCodigoEq.getText(),
                    tipo = cmbTipoEq.getSelectedItem().toString(),
                    gerenteString = cmbGerenteEq.getSelectedItem().toString(),
                    senha;
                
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                Date data = null;
                try {
                    data = formato.parse(dataString);
                } catch (ParseException ex) {
                    Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                int codigo = Integer.parseInt(codigoString);
                
                // cria uma nova senha
                senha = JOptionPane.showInputDialog(null, "Determine uma senha para o novo funcionário", "Definição de senha", JOptionPane.PLAIN_MESSAGE);
                
                // adiciona o novo funcionário ao banco de dados
                if(tipo.equals("Gerente")){
                    Gerente funcionario = new Gerente(senha, codigo, nome, cpf, data);
                    bdFunc.adicionarPessoa(funcionario);
                }
                else if(tipo.equals("Caixa")){ // caso seja um caixa, encontra o gerente correspondente
                    Gerente gerente = bdFunc.buscarGerente(gerenteString);
                    Caixa funcionario = new Caixa(gerente, senha, codigo, nome, cpf, data);
                    bdFunc.adicionarPessoa(funcionario);
                }
                
            }
            updateFuncionarios(); 
        }
        else if("edit".equals(action)){
            int i = tableEquipe.getSelectedRow(); // edita o funcionário selecionado
            
            // ao selecionar um funcionário na tabela, o conteúdo dos campos de texto e das combo boxes é atualizado para os dados do funcionário selecionado
            // logo, para confirmar a edição dos dados basta apenas coletar os dados dos campos assim como na criação de um novo funcioário
        
            if(i >= 0 && i < totalFunc) {
                if(txtfCodigoEq.getText().equals("")|| txtfNomeEq.getText().equals("")|| txtfDataEq.getText().equals("")||
                    txtfCPFEq.getText().equals("")||cmbTipoEq.getSelectedIndex()==0||(cmbTipoEq.getSelectedIndex()==1 && cmbGerenteEq.getSelectedIndex()==0)){
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                }
                else{
                    String nome = txtfNomeEq.getText(),
                        cpf = txtfCPFEq.getText(),
                        dataString = txtfDataEq.getText(),
                        codigoString = txtfCodigoEq.getText(),
                        tipo = cmbTipoEq.getSelectedItem().toString(),
                        gerenteString = cmbGerenteEq.getSelectedItem().toString(),
                        senha = funcAtual.get(3); // a senha não pode ser alterada

                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    Date data = null;
                    try {
                        data = formato.parse(dataString);
                    } catch (ParseException ex) {
                        Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    int codigo = Integer.parseInt(codigoString);
                                        
                    bdFunc.removerPessoa(funcAtual.get(1)); // remove funcionario do banco de dados pelo cpf

                    // adiciona o "novo funcionário" ao banco de dados
                    if(tipo.equals("Gerente")){
                        Gerente funcionario = new Gerente(senha, codigo, nome, cpf, data);
                        bdFunc.adicionarPessoa(funcionario);
                    }
                    else if(tipo.equals("Caixa")){
                        Gerente gerente = bdFunc.buscarGerente(gerenteString);
                        Caixa funcionario = new Caixa(gerente, senha, codigo, nome, cpf, data);
                        bdFunc.adicionarPessoa(funcionario);
                    }
                }
            }   
            updateFuncionarios();
        }
        else if("search".equals(action)){
            tableEquipe.removeAll();
            DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Nome", "CPF", "Data de Nascimento", "Código", "Cargo", "Gerente"}, 0);

            String nome = txtfNomeEq.getText(),
                    cpf = txtfCPFEq.getText(),
                    data = txtfDataEq.getText(),
                    codigo = txtfCodigoEq.getText(),
                    tipo = cmbTipoEq.getSelectedItem().toString(),
                    gerente = cmbGerenteEq.getSelectedItem().toString();
            
            if(tipo.equals("Selecione")){
                tipo = ""; // desconsidera o tipo "Selecione"
            }
            
            for(String func : funcionarios){ // busca em todos os funcionários
                // caso o campo de busca esteja vazio, ele será desconsiderado na busca (uma vez que toda string contém a string vazia)
                String[] f = func.split("_");
                if(f[0].contains(nome) &&
                        f[1].contains(cpf) &&
                        f[2].contains(data) &&
                        f[4].contains(codigo) &&
                        f[5].contains(tipo)){
                    if(gerente.equals("Selecione")||(f[5].equals("Caixa") && f[8].equals(gerente))){
                        // caso o funcionário se enquadre na busca, ele será mostrado na tabela
                        String g = "--";
                        if(f[5].equals("Caixa")){
                            g = f[8];
                        }
                        Object linha[] = new Object[]{
                        f[0],
                        f[1],
                        f[2],
                        f[4],
                        f[5],
                        g};

                        tabela.addRow(linha);
                    }
                }
            }
            tableEquipe.setModel(tabela);
        }
        disableEquipe();
    }//GEN-LAST:event_btnConfirmarEqActionPerformed

    private void btnEditarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEqActionPerformed
        action = "edit";        
        enableEquipe();
    }//GEN-LAST:event_btnEditarEqActionPerformed

    private void btnPesquisarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEqActionPerformed
        action = "search";        
        enableEquipe();
    }//GEN-LAST:event_btnPesquisarEqActionPerformed

    private void btnCancelarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEqActionPerformed
        disableEquipe();
    }//GEN-LAST:event_btnCancelarEqActionPerformed

    private void btnEditarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProd1ActionPerformed
        action = "delete";
        
        if (rowClick >= 0 && rowClick < allProducts.size()){
            //cmbTipoProd.setSelectedItem(cmbTipoProd.getSelectedItem()); //caso o usuário clique no botão após escolher um produto reseta a combo box para os campos específicos ativarem
            
            Produtos selectedProd = allProducts.get(rowClick);
            
            txtfCodigoProd.setText(Integer.toString(selectedProd.getCodigoProd()));
            
            //enableBaseFields();
            
            btnConfirmarEst.setEnabled(true);
        } else {
            txtfCodigoProd.setText("");
            disableBaseFields();
        }
        btnCancelarEst.setEnabled(true);
    }//GEN-LAST:event_btnEditarProd1ActionPerformed

    private void tableEquipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEquipeMouseClicked
        int row = tableEquipe.getSelectedRow();
        
        if (row >= 0 && row < funcionarios.size()){
            // muda os campos de texto e combo boxes para os dados do funcionário selecionado
            txtfNomeEq.setText(tableEquipe.getModel().getValueAt(row, 0).toString());
            txtfCPFEq.setText(tableEquipe.getModel().getValueAt(row, 1).toString());
            txtfDataEq.setText(tableEquipe.getModel().getValueAt(row, 2).toString());
            txtfCodigoEq.setText(tableEquipe.getModel().getValueAt(row, 3).toString());
            
            if(tableEquipe.getModel().getValueAt(row, 4).toString().equals("Caixa")){
                cmbTipoEq.setSelectedIndex(1);
            }
            else{
                cmbTipoEq.setSelectedIndex(2);
            }
            
            for(int i = 0; i < cmbGerenteEq.getItemCount(); i++){
                if(cmbGerenteEq.getItemAt(i).equals(tableEquipe.getModel().getValueAt(row, 5).toString())){
                    cmbGerenteEq.setSelectedIndex(i);
                    break;
                }
            }
            
            // seleciona o funcionário do banco de dados correspondente à seleção
            funcAtual = bdFunc.buscarPessoa(txtfNomeEq.getText() + " " +
                    txtfCPFEq.getText() + " " +
                    txtfDataEq.getText() + " ");
        }
    }//GEN-LAST:event_tableEquipeMouseClicked

    private void txtfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfQuantidadeActionPerformed

    public void disableBaseFields(){
        cmbTipoProd.setEnabled(false);
        txtfQuantidade.setEnabled(false);
        txtfCodigoProd.setEnabled(false);
        txtfFaixaEtaria.setEnabled(false);
        txtfPreco.setEnabled(false);
        txtfNome.setEnabled(false);
        txtfAno.setEnabled(false);
        btnConfirmarEst.setEnabled(false);
        btnCancelarEst.setEnabled(false);
    }
    
    public void disableEquipe(){
        cmbTipoEq.setEnabled(false);
        cmbGerenteEq.setEnabled(false);
        cmbTipoEq.setSelectedIndex(0);
        cmbGerenteEq.setSelectedIndex(0);
        txtfDataEq.setEnabled(false);
        txtfCPFEq.setEnabled(false);
        txtfNomeEq.setEnabled(false);
        txtfCodigoEq.setEnabled(false);
        txtfDataEq.setText("");
        txtfCPFEq.setText("");
        txtfNomeEq.setText("");
        txtfCodigoEq.setText("");
        btnConfirmarEq.setEnabled(false);
        btnCancelarEq.setEnabled(false);
    }
    
    public void enableBaseFields(){
        cmbTipoProd.setEnabled(true);
        txtfQuantidade.setEnabled(true);
        txtfCodigoProd.setEnabled(true);
        //txtfCodigoProd.setText("");
        txtfFaixaEtaria.setEnabled(true);
        txtfPreco.setEnabled(true);
        txtfNome.setEnabled(true);
        txtfAno.setEnabled(true);
        btnCancelarEst.setEnabled(true);
    }
    
    public void enableEquipe(){
        cmbTipoEq.setEnabled(true);
        cmbGerenteEq.setEnabled(true);
        txtfDataEq.setEnabled(true);
        txtfCPFEq.setEnabled(true);
        txtfNomeEq.setEnabled(true);
        txtfCodigoEq.setEnabled(true);
        btnConfirmarEq.setEnabled(true);
        btnCancelarEq.setEnabled(true);
    }
    
    public void clearFields(){
        cmbTipoProd.setSelectedItem("Selecione");
        txtfQuantidade.setEnabled(false);
        txtfQuantidade.setText("/");
        txtfCodigoProd.setText("");
        txtfFaixaEtaria.setText("");
        txtfPreco.setText("");
        txtfNome.setText("");
        txtfAno.setText("");
        txtfVar1.setText("");
        txtfVar2.setText("");
        txtfVar3.setText("");
        txtfVar4.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEq;
    private javax.swing.JButton btnCancelarEst;
    private javax.swing.JButton btnConfirmarEq;
    private javax.swing.JButton btnConfirmarEst;
    private javax.swing.JButton btnEditarEq;
    private javax.swing.JButton btnEditarProd;
    private javax.swing.JButton btnEditarProd1;
    private javax.swing.JButton btnNovoFunc;
    private javax.swing.JButton btnNovoProd;
    private javax.swing.JButton btnPesquisarEq;
    private javax.swing.JButton btnPesquisarProd;
    private javax.swing.JButton btnVoltarEq;
    private javax.swing.JButton btnVoltarEst;
    private javax.swing.JComboBox<String> cmbGerenteEq;
    private javax.swing.JComboBox<String> cmbTipoEq;
    private javax.swing.JComboBox<String> cmbTipoProd;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCodigoEq;
    private javax.swing.JLabel lblCodigoProd;
    private javax.swing.JLabel lblDataEq;
    private javax.swing.JLabel lblFaixaEtaria;
    private javax.swing.JLabel lblGerente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeEq;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuantTipo;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTipoEq;
    private javax.swing.JLabel lblTipoProd;
    private javax.swing.JLabel lblTotalCaixas;
    private javax.swing.JLabel lblTotalGerentes;
    private javax.swing.JLabel lblTotalProd;
    private javax.swing.JLabel lblVar1;
    private javax.swing.JLabel lblVar2;
    private javax.swing.JLabel lblVar3;
    private javax.swing.JLabel lblVar4;
    private javax.swing.JMenu menuAreaGr;
    private javax.swing.JMenuBar menuBarAreaGr;
    private javax.swing.JMenuItem menuSairAreaGr;
    private javax.swing.JMenuItem menuVoltarAreaGr;
    private javax.swing.JPanel pnlEquipe;
    private javax.swing.JPanel pnlEstoque;
    private javax.swing.JPanel pnlGerente;
    private javax.swing.JScrollPane scrlEquipe;
    private javax.swing.JScrollPane scrlProdutos;
    private javax.swing.JPopupMenu.Separator separatorAreaGr;
    private javax.swing.JTabbedPane tabbedPnlGerente;
    private javax.swing.JTable tableEquipe;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtfAno;
    private javax.swing.JTextField txtfCPFEq;
    private javax.swing.JTextField txtfCodigoEq;
    private javax.swing.JTextField txtfCodigoProd;
    private javax.swing.JTextField txtfDataEq;
    private javax.swing.JTextField txtfFaixaEtaria;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfNomeEq;
    private javax.swing.JTextField txtfPreco;
    private javax.swing.JTextField txtfQuantidade;
    private javax.swing.JTextField txtfVar1;
    private javax.swing.JTextField txtfVar2;
    private javax.swing.JTextField txtfVar3;
    private javax.swing.JTextField txtfVar4;
    // End of variables declaration//GEN-END:variables
}
