/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import boxbuster.Alugar;
import boxbuster.BancoDeDadosClientes;
import boxbuster.Cliente;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AreaCliente extends javax.swing.JFrame {

    Cliente clienteAtual = BancoDeDadosClientes.getClienteAtual();
    
    ArrayList<Alugar> histAlugueis = BancoDeDadosClientes.getHistoricoCliente(clienteAtual.getCPF());
    
    /**
     * Creates new form AreaCliente
     */
    public AreaCliente() {
        setLocationRelativeTo(null);
        initComponents();
        lblNome.setText("Nome: " + BancoDeDadosClientes.getClienteAtual().getNome());
        lblCPF.setText("CPF: " + BancoDeDadosClientes.getClienteAtual().getCPF());
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = formatador.format(BancoDeDadosClientes.getClienteAtual().getDataNascimento());
        lblDataNasc.setText("Data de nasc.: " + dataFormatada);
        LocalDate dataAtual = LocalDate.now();
        LocalDate dataNascimento = BancoDeDadosClientes.getClienteAtual().getDataNascimento().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int idade = Period.between(dataNascimento, dataAtual).getYears();
        lblIdade.setText("Idade: " + String.valueOf(idade));
        lblDivida.setText("Divida: " + String.valueOf(BancoDeDadosClientes.getClienteAtual().getDivida()));
        lblProdutosAlugados.setText("Produtos Alugados: " + String.valueOf(BancoDeDadosClientes.getClienteAtual().getAlugados().size()));
    }

    private void updateProdList() {
        histAlugueis = BancoDeDadosClientes.getHistoricoCliente(clienteAtual.getCPF());
        
        //DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Código", "Tipo", "Nome", "Faixa", "Ano", "Preço", "Disp./Alugados"}, 0);

        //for(int i = 0; i < allProducts.size(); i++){
        //    Object linha[] = new Object[]{
        //    allProducts.get(i).getCodigoProd(),
        //    allProducts.get(i).getClass().getSimpleName(), 
        //    allProducts.get(i).getNomeProd(),
        //    allProducts.get(i).getFaixaEtaria(),
        //    allProducts.get(i).getAno(),
        //    allProducts.get(i).getPreco(),
        //    allProducts.get(i).getDisponiveis() + "/" + allProducts.get(i).getAlugados()};

        //    tabela.addRow(linha);
        //}
        
        //tableProdutos.setModel(tabela);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAreaCliente = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblDivida = new javax.swing.JLabel();
        lblProdutosAlugados = new javax.swing.JLabel();
        btnDeslogar = new javax.swing.JButton();
        btnLojaMain = new javax.swing.JButton();
        logoBoxbuster = new javax.swing.JLabel();
        separator2AreaCli = new javax.swing.JSeparator();
        lblHistAluguel = new javax.swing.JLabel();
        scrlAluguel = new javax.swing.JScrollPane();
        tableAluguel = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        menuBarAreaCli = new javax.swing.JMenuBar();
        menuAreaCli = new javax.swing.JMenu();
        menuVoltarAreaCli = new javax.swing.JMenuItem();
        separator1AreaCli = new javax.swing.JPopupMenu.Separator();
        menuSairAreaCli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do cliente");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogo.png")).getImage());

        pnlAreaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Área do Cliente"));

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setText("Suas informações:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome: -----");

        lblDataNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataNasc.setText("Data de nasc.: 00/00/0000");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF: 000.000.000-00");

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdade.setText("Idade: --");

        lblDivida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDivida.setText("Dívida: R$ --,--");

        lblProdutosAlugados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProdutosAlugados.setText("Produtos Alugados: --");

        btnDeslogar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeslogar.setText("Deslogar");
        btnDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeslogarActionPerformed(evt);
            }
        });

        btnLojaMain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLojaMain.setText("Ir para a loja");
        btnLojaMain.setToolTipText("Ver produtos");
        btnLojaMain.setRequestFocusEnabled(false);
        btnLojaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLojaMainActionPerformed(evt);
            }
        });

        logoBoxbuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogoBig.png"))); // NOI18N

        lblHistAluguel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHistAluguel.setText("Histórico de Aluguel:");

        tableAluguel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Produto", "Tipo", "Data Inicial", "Devolução", "Preço", "Dívida", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlAluguel.setViewportView(tableAluguel);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDevolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAreaClienteLayout = new javax.swing.GroupLayout(pnlAreaCliente);
        pnlAreaCliente.setLayout(pnlAreaClienteLayout);
        pnlAreaClienteLayout.setHorizontalGroup(
            pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlAluguel)
            .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator2AreaCli)
                    .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                        .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaClienteLayout.createSequentialGroup()
                                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(lblNome)
                                    .addComponent(lblDivida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdade)
                                    .addComponent(lblDataNasc)
                                    .addComponent(lblProdutosAlugados))
                                .addGap(60, 60, 60))
                            .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(lblInfo))
                                    .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                                        .addComponent(btnDeslogar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLojaMain)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(logoBoxbuster)
                        .addGap(35, 35, 35))
                    .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                        .addComponent(lblHistAluguel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAreaClienteLayout.setVerticalGroup(
            pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoBoxbuster, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAreaClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfo)
                        .addGap(18, 18, 18)
                        .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblDataNasc))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(lblIdade))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDivida)
                            .addComponent(lblProdutosAlugados))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeslogar)
                            .addComponent(btnLojaMain)
                            .addComponent(btnEditar))))
                .addGap(6, 6, 6)
                .addComponent(separator2AreaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAreaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHistAluguel)
                    .addComponent(btnDevolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        menuAreaCli.setText("Menu");

        menuVoltarAreaCli.setText("Voltar");
        menuVoltarAreaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarAreaCliActionPerformed(evt);
            }
        });
        menuAreaCli.add(menuVoltarAreaCli);
        menuAreaCli.add(separator1AreaCli);

        menuSairAreaCli.setText("Sair");
        menuSairAreaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairAreaCliActionPerformed(evt);
            }
        });
        menuAreaCli.add(menuSairAreaCli);

        menuBarAreaCli.add(menuAreaCli);

        setJMenuBar(menuBarAreaCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVoltarAreaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarAreaCliActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVoltarAreaCliActionPerformed

    private void btnLojaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLojaMainActionPerformed
        new Loja().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLojaMainActionPerformed

    private void btnDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeslogarActionPerformed
        BancoDeDadosClientes.setClienteAtual(null);
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeslogarActionPerformed

    private void menuSairAreaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairAreaCliActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairAreaCliActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        new EditarCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaCliente().setVisible(true);
            }
        });
    }
    
    public void alterarNome(String novoNome) {
        lblNome.setText("Nome: " + novoNome);
    }
     
    public void alterarCPF(String novoCPF) {
        lblCPF.setText("CPF: " + novoCPF);
    }
    
    public void alterarDataNascimento(String novaDataNascimento) {
        lblDataNasc.setText("Data de nasc: " + novaDataNascimento);
    }
    
    public void alterarDivida(String novaDivida) {
        lblDivida.setText("Dívida: R$ " + novaDivida);
    }
    
    public void alterarAlugados(String novoAlugados){
        lblProdutosAlugados.setText("Produtos Alugados: " + novoAlugados);
    }
    
    public void alterarIdade(String novaIdade){
        lblIdade.setText("Idade: " + novaIdade);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeslogar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLojaMain;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblDivida;
    private javax.swing.JLabel lblHistAluguel;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProdutosAlugados;
    private javax.swing.JLabel logoBoxbuster;
    private javax.swing.JMenu menuAreaCli;
    private javax.swing.JMenuBar menuBarAreaCli;
    private javax.swing.JMenuItem menuSairAreaCli;
    private javax.swing.JMenuItem menuVoltarAreaCli;
    private javax.swing.JPanel pnlAreaCliente;
    private javax.swing.JScrollPane scrlAluguel;
    private javax.swing.JPopupMenu.Separator separator1AreaCli;
    private javax.swing.JSeparator separator2AreaCli;
    private javax.swing.JTable tableAluguel;
    // End of variables declaration//GEN-END:variables
}
