package telas;

import boxbuster.Alugar;
import boxbuster.Pedido;
import boxbuster.Produtos;
import boxbuster.Status;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author elisrb
 */
public class AreaCaixa extends javax.swing.JFrame {

    HashMap<Integer, Alugar> histAlugueis;
    String codigoAtual;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    
    /**
     * Creates new form AreaCaixa
     */
    public AreaCaixa() {
        setLocationRelativeTo(null);
        initComponents();
    }
    
    private void updateHistList() { // formata atualiza a tabela de pedidos
        tableAluguel.removeAll();
        
        histAlugueis = Pedido.loadAlugueis(); // retorna um HashMap com todos os Alugueis da loja
        
        DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Pedido", "Produto", "Tipo", "Data Inicial", "Devolução", "Preço", "Dívida", "Status"}, 0);
        for(Alugar aluguel : histAlugueis.values()){
            
            if(aluguel.getCaixaCodigo().equals(codigoAtual)){ // analisa cada pedido e coleta somente os que têm o código do caixa que está logado
                for(int j = 0; j < aluguel.getListaProdutos().size(); j++){ // analisa cada produto de cada pedido separadamente
                    Produtos item = aluguel.getListaProdutos().get(j);
                    Status status = aluguel.getProdutoStatus(item.getCodigoProd());

                    double divida = 0;
                    if(status == Status.ATRASADO){
                        divida = item.getPreco() / 2;
                    }
                    Object linha[] = new Object[]{
                    aluguel.getCodigoPedido(),
                    item.getNomeProd(),
                    item.getClass().getSimpleName(), 
                    formato.format(aluguel.getDataPedido()),
                    formato.format(aluguel.getDataDevolucao()),
                    item.getPreco(),
                    divida,
                    status};

                   tabela.addRow(linha);
                }
            }
        }
        tableAluguel.setModel(tabela);  
    }
    
    public void alterarNome(String novoNome) {
        lblNome.setText("Nome: " + novoNome);
    }
     
    public void alterarCPF(String novoCPF) {
        lblCPF.setText("CPF: " + novoCPF);
    }
    
    public void alterarDataNascimento(String novaDataNascimento) {
        lblDataNasc.setText("Data de nasc: " + novaDataNascimento);
    }
    
    public void alterarIdade(String novaIdade){
        lblIdade.setText("Idade: " + novaIdade);
    }
    
    public void alterarCodigo(String novoCodigo){
        lblCodigo.setText("Código: " + novoCodigo);
        codigoAtual = novoCodigo;
        updateHistList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnlAreaCx = new javax.swing.JPanel();
        lblInformacoes = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblIdade = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        separator2AreaCx = new javax.swing.JSeparator();
        lblHistAluguel = new javax.swing.JLabel();
        txtCodigoPesquisa = new javax.swing.JLabel();
        txtfCodigoPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        scrlPedidos = new javax.swing.JScrollPane();
        tableAluguel = new javax.swing.JTable();
        menuBarAreaCx = new javax.swing.JMenuBar();
        menuAreaCx = new javax.swing.JMenu();
        menuVoltarAreaCx = new javax.swing.JMenuItem();
        separator1AreaCx = new javax.swing.JPopupMenu.Separator();
        menuSairAreaCx = new javax.swing.JMenuItem();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Tipo", "Nome", "Idade", "CPF", "Gerente"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área do caixa");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogo.png")).getImage());

        pnlAreaCx.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Área do caixa"), "Área do Caixa"));

        lblInformacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInformacoes.setText("Suas informações:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome: -----");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigo.setText("Código: -----");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF 000.000.000-00");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdade.setText("Idade: --");

        lblDataNasc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataNasc.setText("Data de nascimento: 00/00/0000");

        lblHistAluguel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHistAluguel.setText("Histórico de pedidos:");

        txtCodigoPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoPesquisa.setText("Código do Pedido:");

        txtfCodigoPesquisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPesquisar.setText("Pesquisar Pedido");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tableAluguel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Quantidade", "Produtos", "Cliente", "Preço", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlPedidos.setViewportView(tableAluguel);

        javax.swing.GroupLayout pnlAreaCxLayout = new javax.swing.GroupLayout(pnlAreaCx);
        pnlAreaCx.setLayout(pnlAreaCxLayout);
        pnlAreaCxLayout.setHorizontalGroup(
            pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator2AreaCx)
            .addGroup(pnlAreaCxLayout.createSequentialGroup()
                .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAreaCxLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblHistAluguel))
                    .addGroup(pnlAreaCxLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblInformacoes)))
                .addGap(66, 228, Short.MAX_VALUE))
            .addGroup(pnlAreaCxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAreaCxLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtCodigoPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(txtfCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAreaCxLayout.createSequentialGroup()
                        .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaCxLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(151, 151, 151))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaCxLayout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGap(149, 149, 149)))
                        .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdade)
                            .addComponent(lblCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataNasc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addComponent(scrlPedidos, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlAreaCxLayout.setVerticalGroup(
            pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaCxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacoes)
                .addGap(18, 18, 18)
                .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblCodigo)
                    .addComponent(lblCPF))
                .addGap(24, 24, 24)
                .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lblDataNasc)
                    .addComponent(lblIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator2AreaCx, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHistAluguel)
                .addGap(12, 12, 12)
                .addGroup(pnlAreaCxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPesquisa)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        menuAreaCx.setText("Menu");

        menuVoltarAreaCx.setText("Voltar");
        menuVoltarAreaCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarAreaCxActionPerformed(evt);
            }
        });
        menuAreaCx.add(menuVoltarAreaCx);
        menuAreaCx.add(separator1AreaCx);

        menuSairAreaCx.setText("Sair");
        menuAreaCx.add(menuSairAreaCx);

        menuBarAreaCx.add(menuAreaCx);

        setJMenuBar(menuBarAreaCx);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaCx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreaCx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVoltarAreaCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarAreaCxActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVoltarAreaCxActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // o algoritmo é o mesmo do updateHistList, mas tem uma condição a mais que checa se o código do pedido contém o conteúdo do campo de busca
        // para visualizar todos os pedidos, basta pesquisar por um código vazio
        
        tableAluguel.removeAll();
        
        histAlugueis = Pedido.loadAlugueis();
        
        DefaultTableModel tabela = new DefaultTableModel(new Object[] {"Pedido", "Produto", "Tipo", "Data Inicial", "Devolução", "Preço", "Dívida", "Status"}, 0);
        for(int i = 0; i < histAlugueis.size(); i++){
            Alugar aluguel = histAlugueis.get(i);
            if(aluguel.getCaixaCodigo().equals(codigoAtual) && String.valueOf(aluguel.getCodigoPedido()).contains(txtfCodigoPesquisa.getText())){
                for(int j = 0; j < histAlugueis.get(i).getListaProdutos().size(); j++){
                    Produtos item = aluguel.getListaProdutos().get(j);
                    Status status = aluguel.getProdutoStatus(item.getCodigoProd());

                    double divida = 0;
                    if(status == Status.ATRASADO){
                        divida = item.getPreco() / 2;
                    }
                    
                    Object linha[] = new Object[]{
                    aluguel.getCodigoPedido(),
                    item.getNomeProd(),
                    item.getClass().getSimpleName(), 
                    formato.format(aluguel.getDataPedido()),
                    formato.format(aluguel.getDataDevolucao()),
                    item.getPreco(),
                    divida,
                    status};

                   tabela.addRow(linha);
                }
            }
        }
        tableAluguel.setModel(tabela);  
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaCaixa().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblHistAluguel;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JMenu menuAreaCx;
    private javax.swing.JMenuBar menuBarAreaCx;
    private javax.swing.JMenuItem menuSairAreaCx;
    private javax.swing.JMenuItem menuVoltarAreaCx;
    private javax.swing.JPanel pnlAreaCx;
    private javax.swing.JScrollPane scrlPedidos;
    private javax.swing.JPopupMenu.Separator separator1AreaCx;
    private javax.swing.JSeparator separator2AreaCx;
    private javax.swing.JTable tableAluguel;
    private javax.swing.JLabel txtCodigoPesquisa;
    private javax.swing.JTextField txtfCodigoPesquisa;
    // End of variables declaration//GEN-END:variables
}
