/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Adm
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        setLocationRelativeTo(null);
        initComponents();
        txtfNome.setEnabled(false);
        txtfCPF.setEnabled(false);
        txtfDataNascimento.setEnabled(false);
        lblSenha.setVisible(false);
        txtfSenha.setVisible(false);
        txtfSenha.setEnabled(false);
        btnCadastrar.setEnabled(false);
        btnPerfil.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadCli = new javax.swing.JPanel();
        lblPropaganda1 = new javax.swing.JLabel();
        lblPropaganda2 = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        cmbSituacao = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        txtfNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtfCPF = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtfDataNascimento = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtfSenha = new javax.swing.JTextField();
        logoBoxbuster = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnLoja = new javax.swing.JButton();
        menuBarCadCli = new javax.swing.JMenuBar();
        menuCadCli = new javax.swing.JMenu();
        menuVoltarCadCli = new javax.swing.JMenuItem();
        separator1CadCli = new javax.swing.JPopupMenu.Separator();
        menuSairCadCli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de cadastro");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogo.png")).getImage());

        pnlCadCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Cliente"));

        lblPropaganda1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPropaganda1.setForeground(new java.awt.Color(255, 0, 0));
        lblPropaganda1.setText("CLIENTES CADASTRADOS GANHAM DIVERSOS BENEFÍCIOS");

        lblPropaganda2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPropaganda2.setForeground(new java.awt.Color(255, 0, 0));
        lblPropaganda2.setText("INCLUINDO DESCONTO EM TODOS OS PRODUTOS!");

        lblSituacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSituacao.setText("Você quer se cadastrar?");

        cmbSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Quero me cadastrar", "Não quero me cadastrar", "Já sou cadastrado" }));
        cmbSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSituacaoActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        lblNome.setToolTipText("");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setText("CPF:");

        lblDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataNascimento.setText("Data de nascimento:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        txtfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfSenhaActionPerformed(evt);
            }
        });

        logoBoxbuster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogoBig.png"))); // NOI18N

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar-se");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPerfil.setText("Ver perfil");
        btnPerfil.setEnabled(false);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLoja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoja.setText("Entrar e ir à loja");
        btnLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadCliLayout = new javax.swing.GroupLayout(pnlCadCli);
        pnlCadCli.setLayout(pnlCadCliLayout);
        pnlCadCliLayout.setHorizontalGroup(
            pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoja)
                        .addContainerGap())
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCadCliLayout.createSequentialGroup()
                                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblCPF)
                                    .addComponent(lblDataNascimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfNome)
                                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoBoxbuster)
                        .addGap(40, 40, 40))))
            .addGroup(pnlCadCliLayout.createSequentialGroup()
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblPropaganda1))
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addGap(18, 18, 18)
                        .addComponent(txtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblPropaganda2)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(pnlCadCliLayout.createSequentialGroup()
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerfil))
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSituacao)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCadCliLayout.setVerticalGroup(
            pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPropaganda1)
                .addGap(2, 2, 2)
                .addComponent(lblPropaganda2)
                .addGap(3, 3, 3)
                .addComponent(lblSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoBoxbuster)
                    .addGroup(pnlCadCliLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCPF)
                            .addComponent(txtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataNascimento)
                            .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSenha)
                            .addComponent(txtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnLoja))
                .addContainerGap())
        );

        menuCadCli.setText("Menu");

        menuVoltarCadCli.setText("Voltar");
        menuVoltarCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarCadCliActionPerformed(evt);
            }
        });
        menuCadCli.add(menuVoltarCadCli);
        menuCadCli.add(separator1CadCli);

        menuSairCadCli.setText("Sair");
        menuSairCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairCadCliActionPerformed(evt);
            }
        });
        menuCadCli.add(menuSairCadCli);

        menuBarCadCli.add(menuCadCli);

        setJMenuBar(menuBarCadCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCadCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVoltarCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarCadCliActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVoltarCadCliActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        new AreaCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLojaActionPerformed
        new Loja().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLojaActionPerformed

    private void txtfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfSenhaActionPerformed
        new AreaCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtfSenhaActionPerformed

    private void cmbSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSituacaoActionPerformed
        int index = cmbSituacao.getSelectedIndex();
        if(index == 1 || index == 3){
            txtfNome.setEnabled(true);
            txtfCPF.setEnabled(true);
            txtfDataNascimento.setEnabled(true);
            lblSenha.setVisible(true);
            txtfSenha.setVisible(true);
            txtfSenha.setEnabled(true);
            btnCadastrar.setEnabled(true);
            btnPerfil.setEnabled(true);
            
        }
        else if(index == 2){
            txtfNome.setEnabled(true);
            txtfCPF.setEnabled(true);
            txtfDataNascimento.setEnabled(true);
            lblSenha.setVisible(false);
            txtfSenha.setVisible(false);
            txtfSenha.setEnabled(false);
            btnCadastrar.setEnabled(true);
            btnPerfil.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmbSituacaoActionPerformed

    private void menuSairCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairCadCliActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairCadCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLoja;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbSituacao;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPropaganda1;
    private javax.swing.JLabel lblPropaganda2;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel logoBoxbuster;
    private javax.swing.JMenuBar menuBarCadCli;
    private javax.swing.JMenu menuCadCli;
    private javax.swing.JMenuItem menuSairCadCli;
    private javax.swing.JMenuItem menuVoltarCadCli;
    private javax.swing.JPanel pnlCadCli;
    private javax.swing.JPopupMenu.Separator separator1CadCli;
    private javax.swing.JTextField txtfCPF;
    private javax.swing.JTextField txtfDataNascimento;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfSenha;
    // End of variables declaration//GEN-END:variables
}
