package telas;

import boxbuster.BancoDeDadosClientes;
import boxbuster.Cadastrado;
import boxbuster.Visitante;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author elisrb
 */
public class EditarCliente extends javax.swing.JFrame {
    
    //inicia o banco de dados
    BancoDeDadosClientes bdClientes = new BancoDeDadosClientes();
    
    public EditarCliente() { // inicia a tela com as informações do cliente e permitindo ele editá-las
        setLocationRelativeTo(null);
        initComponents();
        
        if(BancoDeDadosClientes.getClienteAtual().getClass().getSimpleName().equals("Cadastrado")){
            lblSenha.setVisible(true);
            txtfSenha.setVisible(true);
            txtfNome.setText(BancoDeDadosClientes.getClienteAtual().getNome());
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formatador.format(BancoDeDadosClientes.getClienteAtual().getDataNascimento());
            txtfDataNascimento.setText(dataFormatada);
        } else {
            lblSenha.setVisible(false);
            txtfSenha.setVisible(false);
            txtfNome.setText(BancoDeDadosClientes.getClienteAtual().getNome());
            SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formatador.format(BancoDeDadosClientes.getClienteAtual().getDataNascimento());
            txtfDataNascimento.setText(dataFormatada); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditCli = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtfSenha = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtfNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        txtfDataNascimento = new javax.swing.JFormattedTextField();
        menuBarEditCli = new javax.swing.JMenuBar();
        menuEditCli = new javax.swing.JMenu();
        menuVoltarEditCli = new javax.swing.JMenuItem();
        separatorEditCli = new javax.swing.JPopupMenu.Separator();
        menuSairEditCli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar perfil");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogo.png")).getImage());

        pnlEditCli.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Informações"));
        pnlEditCli.setToolTipText("");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Nome:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataNascimento.setText("Data de Nasc.:");

        try {
            txtfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlEditCliLayout = new javax.swing.GroupLayout(pnlEditCli);
        pnlEditCli.setLayout(pnlEditCliLayout);
        pnlEditCliLayout.setHorizontalGroup(
            pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditCliLayout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addGroup(pnlEditCliLayout.createSequentialGroup()
                        .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlEditCliLayout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfNome))
                            .addGroup(pnlEditCliLayout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addGap(18, 18, 18)
                                .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEditCliLayout.createSequentialGroup()
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEditCliLayout.setVerticalGroup(
            pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCliLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(txtfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        menuEditCli.setText("Menu");

        menuVoltarEditCli.setText("Voltar");
        menuVoltarEditCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarEditCliActionPerformed(evt);
            }
        });
        menuEditCli.add(menuVoltarEditCli);
        menuEditCli.add(separatorEditCli);

        menuSairEditCli.setText("Sair");
        menuSairEditCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairEditCliActionPerformed(evt);
            }
        });
        menuEditCli.add(menuSairEditCli);

        menuBarEditCli.add(menuEditCli);

        setJMenuBar(menuBarEditCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEditCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEditCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // salva as novas informações após a edição
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(BancoDeDadosClientes.getClienteAtual().getClass().getSimpleName().equals("Cadastrado")){
            if(txtfNome.getText().equals("") || txtfDataNascimento.getText().equals("") || txtfSenha.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Dados mudados com sucesso!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                bdClientes.removerPessoa(BancoDeDadosClientes.getClienteAtual().getCPF());
                String nome = txtfNome.getText();
                String senha = txtfSenha.getText();
                String dataNascimentoString = txtfDataNascimento.getText();
                Date dataNascimento = null;
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                double divida = BancoDeDadosClientes.getClienteAtual().getDivida();
                
                try {
                    dataNascimento = formato.parse(dataNascimentoString);
                } catch (ParseException ex) {
                    Logger.getLogger(LoginCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                Cadastrado cadastrado = new Cadastrado(nome, BancoDeDadosClientes.getClienteAtual().getCPF(), dataNascimento, divida, senha);
                BancoDeDadosClientes.setClienteAtual(cadastrado);
                
                bdClientes.adicionarPessoa(cadastrado);
                
                new AreaCliente().setVisible(true);
                this.setVisible(false);
            }
        } else {
            if(txtfNome.getText().equals("") || txtfDataNascimento.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Dados mudados com sucesso!", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                bdClientes.removerPessoa(BancoDeDadosClientes.getClienteAtual().getCPF());
                String nome = txtfNome.getText();
                String dataNascimentoString = txtfDataNascimento.getText();
                Date dataNascimento = null;
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                double divida = BancoDeDadosClientes.getClienteAtual().getDivida();
                
                try {
                    dataNascimento = formato.parse(dataNascimentoString);
                } catch (ParseException ex) {
                    Logger.getLogger(LoginCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                Visitante visitante = new Visitante(nome, BancoDeDadosClientes.getClienteAtual().getCPF(), dataNascimento, divida);
                
                BancoDeDadosClientes.setClienteAtual(visitante);
                bdClientes.adicionarPessoa(visitante);
                
                new AreaCliente().setVisible(true);
                this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    //volta para a tela principal
    private void menuVoltarEditCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarEditCliActionPerformed
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVoltarEditCliActionPerformed

    private void menuSairEditCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairEditCliActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairEditCliActionPerformed

    //volta para a área do cliente
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new AreaCliente().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JMenuBar menuBarEditCli;
    private javax.swing.JMenu menuEditCli;
    private javax.swing.JMenuItem menuSairEditCli;
    private javax.swing.JMenuItem menuVoltarEditCli;
    private javax.swing.JPanel pnlEditCli;
    private javax.swing.JPopupMenu.Separator separatorEditCli;
    private javax.swing.JFormattedTextField txtfDataNascimento;
    private javax.swing.JTextField txtfNome;
    private javax.swing.JTextField txtfSenha;
    // End of variables declaration//GEN-END:variables
}
