/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Adm
 */
public class Loja extends javax.swing.JFrame {

    /**
     * Creates new form LojaScr
     */
    public Loja() {
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoja = new javax.swing.JPanel();
        tabbedPnlLoja = new javax.swing.JTabbedPane();
        scrollFilmes = new javax.swing.JScrollPane();
        pnlFilmes = new javax.swing.JPanel();
        pnlMv1 = new javax.swing.JPanel();
        imgMv1 = new javax.swing.JLabel();
        nomeMv1 = new javax.swing.JLabel();
        descMv1 = new javax.swing.JLabel();
        precoMv1 = new javax.swing.JLabel();
        btnAlugarMv1 = new javax.swing.JRadioButton();
        btnDetalhesMv1 = new javax.swing.JButton();
        pnlMv2 = new javax.swing.JPanel();
        imgMv2 = new javax.swing.JLabel();
        nomeMv2 = new javax.swing.JLabel();
        descMv2 = new javax.swing.JLabel();
        precoMv2 = new javax.swing.JLabel();
        btnAlugarMv2 = new javax.swing.JRadioButton();
        btnDetalhesMv2 = new javax.swing.JButton();
        pnlMv3 = new javax.swing.JPanel();
        imgMv3 = new javax.swing.JLabel();
        nomeMv3 = new javax.swing.JLabel();
        descMv3 = new javax.swing.JLabel();
        precoMv3 = new javax.swing.JLabel();
        btnAlugarMv3 = new javax.swing.JRadioButton();
        btnDetalhesMv3 = new javax.swing.JButton();
        pnlMv4 = new javax.swing.JPanel();
        imgMv4 = new javax.swing.JLabel();
        nomeMv4 = new javax.swing.JLabel();
        descMv4 = new javax.swing.JLabel();
        precoMv4 = new javax.swing.JLabel();
        btnAlugarMv4 = new javax.swing.JRadioButton();
        btnDetalhesMv4 = new javax.swing.JButton();
        pnlMv5 = new javax.swing.JPanel();
        imgMv5 = new javax.swing.JLabel();
        nomeMv5 = new javax.swing.JLabel();
        descMv5 = new javax.swing.JLabel();
        precoMv5 = new javax.swing.JLabel();
        btnAlugarMv5 = new javax.swing.JRadioButton();
        btnDetalhesMv5 = new javax.swing.JButton();
        pnlMv6 = new javax.swing.JPanel();
        imgMv6 = new javax.swing.JLabel();
        nomeMv6 = new javax.swing.JLabel();
        descMv6 = new javax.swing.JLabel();
        precoMv6 = new javax.swing.JLabel();
        btnAlugarMv6 = new javax.swing.JRadioButton();
        btnDetalhesMv6 = new javax.swing.JButton();
        scrollMusica = new javax.swing.JScrollPane();
        scrollJogos = new javax.swing.JScrollPane();
        btnVoltarLoja = new javax.swing.JButton();
        btnFinalizarLoja = new javax.swing.JButton();
        btnAddCartLoja = new javax.swing.JButton();
        txtCartLoja = new javax.swing.JLabel();
        menuBarLoja = new javax.swing.JMenuBar();
        menuLoja = new javax.swing.JMenu();
        menuFinalizarLoja = new javax.swing.JMenuItem();
        menuVoltarLoja = new javax.swing.JMenuItem();
        separatorLoja = new javax.swing.JPopupMenu.Separator();
        menuSairLoja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollFilmes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlMv1.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/BackToTheFuture.png"))); // NOI18N

        nomeMv1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv1.setText("De Volta para o Futu...");

        descMv1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv1.setText("1985 - DVD/BLU-RAY");

        precoMv1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv1.setText("R$ 20,00");

        btnAlugarMv1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv1.setText("Alugar");

        btnDetalhesMv1.setText("Detalhes");
        btnDetalhesMv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv1Layout = new javax.swing.GroupLayout(pnlMv1);
        pnlMv1.setLayout(pnlMv1Layout);
        pnlMv1Layout.setHorizontalGroup(
            pnlMv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv1)
                    .addComponent(nomeMv1)
                    .addComponent(precoMv1)
                    .addComponent(btnAlugarMv1)
                    .addComponent(btnDetalhesMv1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMv1Layout.setVerticalGroup(
            pnlMv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv1)
                    .addGroup(pnlMv1Layout.createSequentialGroup()
                        .addComponent(nomeMv1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlMv2.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/Matrix.png"))); // NOI18N

        nomeMv2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv2.setText("Matrix");

        descMv2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv2.setText("1999 - DVD/BLU-RAY");

        precoMv2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv2.setText("R$ 20,00");

        btnAlugarMv2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv2.setText("Alugar");

        btnDetalhesMv2.setText("Detalhes");
        btnDetalhesMv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv2Layout = new javax.swing.GroupLayout(pnlMv2);
        pnlMv2.setLayout(pnlMv2Layout);
        pnlMv2Layout.setHorizontalGroup(
            pnlMv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv2)
                    .addComponent(nomeMv2)
                    .addComponent(precoMv2)
                    .addComponent(btnAlugarMv2)
                    .addComponent(btnDetalhesMv2))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlMv2Layout.setVerticalGroup(
            pnlMv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv2)
                    .addGroup(pnlMv2Layout.createSequentialGroup()
                        .addComponent(nomeMv2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMv3.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/TheThing.png"))); // NOI18N

        nomeMv3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv3.setText("O Enigma de Outro...");

        descMv3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv3.setText("1982 - DVD/BLU-RAY");

        precoMv3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv3.setText("R$ 20,00");

        btnAlugarMv3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv3.setText("Alugar");

        btnDetalhesMv3.setText("Detalhes");
        btnDetalhesMv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv3Layout = new javax.swing.GroupLayout(pnlMv3);
        pnlMv3.setLayout(pnlMv3Layout);
        pnlMv3Layout.setHorizontalGroup(
            pnlMv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv3)
                    .addComponent(nomeMv3)
                    .addComponent(precoMv3)
                    .addComponent(btnAlugarMv3)
                    .addComponent(btnDetalhesMv3))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlMv3Layout.setVerticalGroup(
            pnlMv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv3)
                    .addGroup(pnlMv3Layout.createSequentialGroup()
                        .addComponent(nomeMv3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMv4.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/TheLionKing.png"))); // NOI18N

        nomeMv4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv4.setText("O Rei Leão");

        descMv4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv4.setText("1994 - DVD/BLU-RAY");

        precoMv4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv4.setText("R$ 20,00");

        btnAlugarMv4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv4.setText("Alugar");

        btnDetalhesMv4.setText("Detalhes");
        btnDetalhesMv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv4Layout = new javax.swing.GroupLayout(pnlMv4);
        pnlMv4.setLayout(pnlMv4Layout);
        pnlMv4Layout.setHorizontalGroup(
            pnlMv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv4)
                    .addComponent(nomeMv4)
                    .addComponent(precoMv4)
                    .addComponent(btnAlugarMv4)
                    .addComponent(btnDetalhesMv4))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlMv4Layout.setVerticalGroup(
            pnlMv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv4)
                    .addGroup(pnlMv4Layout.createSequentialGroup()
                        .addComponent(nomeMv4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv4)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pnlMv5.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/LordOfTheRings.png"))); // NOI18N

        nomeMv5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv5.setText("O Senhor dos Anéis");

        descMv5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv5.setText("2001 - DVD/BLU-RAY");

        precoMv5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv5.setText("R$ 20,00");

        btnAlugarMv5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv5.setText("Alugar");

        btnDetalhesMv5.setText("Detalhes");
        btnDetalhesMv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv5Layout = new javax.swing.GroupLayout(pnlMv5);
        pnlMv5.setLayout(pnlMv5Layout);
        pnlMv5Layout.setHorizontalGroup(
            pnlMv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv5)
                    .addComponent(nomeMv5)
                    .addComponent(precoMv5)
                    .addComponent(btnAlugarMv5)
                    .addComponent(btnDetalhesMv5))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlMv5Layout.setVerticalGroup(
            pnlMv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv5)
                    .addGroup(pnlMv5Layout.createSequentialGroup()
                        .addComponent(nomeMv5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMv6.setPreferredSize(new java.awt.Dimension(190, 190));

        imgMv6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filmes/Avengers.png"))); // NOI18N

        nomeMv6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeMv6.setText("Os Vingadores");

        descMv6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descMv6.setText("2012 - DVD/BLU-RAY");

        precoMv6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoMv6.setText("R$ 20,00");

        btnAlugarMv6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlugarMv6.setText("Alugar");

        btnDetalhesMv6.setText("Detalhes");
        btnDetalhesMv6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesMv6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMv6Layout = new javax.swing.GroupLayout(pnlMv6);
        pnlMv6.setLayout(pnlMv6Layout);
        pnlMv6Layout.setHorizontalGroup(
            pnlMv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgMv6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descMv6)
                    .addComponent(nomeMv6)
                    .addComponent(precoMv6)
                    .addComponent(btnAlugarMv6)
                    .addComponent(btnDetalhesMv6))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlMv6Layout.setVerticalGroup(
            pnlMv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMv6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMv6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMv6)
                    .addGroup(pnlMv6Layout.createSequentialGroup()
                        .addComponent(nomeMv6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descMv6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoMv6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlugarMv6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalhesMv6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFilmesLayout = new javax.swing.GroupLayout(pnlFilmes);
        pnlFilmes.setLayout(pnlFilmesLayout);
        pnlFilmesLayout.setHorizontalGroup(
            pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFilmesLayout.createSequentialGroup()
                                .addComponent(pnlMv1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlMv2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlFilmesLayout.createSequentialGroup()
                                .addComponent(pnlMv3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlMv4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(pnlFilmesLayout.createSequentialGroup()
                        .addComponent(pnlMv5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMv6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFilmesLayout.setVerticalGroup(
            pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilmesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMv1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(pnlMv2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMv3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(pnlMv4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMv5, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(pnlMv6, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap())
        );

        scrollFilmes.setViewportView(pnlFilmes);

        tabbedPnlLoja.addTab("Filmes", scrollFilmes);
        tabbedPnlLoja.addTab("Música", scrollMusica);
        tabbedPnlLoja.addTab("Jogos", scrollJogos);

        btnVoltarLoja.setText("Voltar");
        btnVoltarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLojaActionPerformed(evt);
            }
        });

        btnFinalizarLoja.setText("Finalizar pedido");

        btnAddCartLoja.setText("Adicionar itens ao carrinho");

        txtCartLoja.setText("Carrinho: 0 itens");

        javax.swing.GroupLayout pnlLojaLayout = new javax.swing.GroupLayout(pnlLoja);
        pnlLoja.setLayout(pnlLojaLayout);
        pnlLojaLayout.setHorizontalGroup(
            pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPnlLoja)
            .addGroup(pnlLojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltarLoja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCartLoja)
                .addGap(18, 18, 18)
                .addComponent(txtCartLoja)
                .addGap(68, 68, 68)
                .addComponent(btnFinalizarLoja)
                .addContainerGap())
        );
        pnlLojaLayout.setVerticalGroup(
            pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLojaLayout.createSequentialGroup()
                .addComponent(tabbedPnlLoja, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarLoja)
                    .addComponent(btnFinalizarLoja)
                    .addComponent(btnAddCartLoja)
                    .addComponent(txtCartLoja))
                .addContainerGap())
        );

        menuLoja.setText("Menu");

        menuFinalizarLoja.setText("Finalizar pedido");
        menuFinalizarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFinalizarLojaActionPerformed(evt);
            }
        });
        menuLoja.add(menuFinalizarLoja);

        menuVoltarLoja.setText("Voltar");
        menuVoltarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarLojaActionPerformed(evt);
            }
        });
        menuLoja.add(menuVoltarLoja);
        menuLoja.add(separatorLoja);

        menuSairLoja.setText("Sair");
        menuLoja.add(menuSairLoja);

        menuBarLoja.add(menuLoja);

        setJMenuBar(menuBarLoja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVoltarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVoltarLojaActionPerformed

    private void menuFinalizarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFinalizarLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFinalizarLojaActionPerformed

    private void btnDetalhesMv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv1ActionPerformed

    private void btnVoltarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarLojaActionPerformed

    private void btnDetalhesMv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv2ActionPerformed

    private void btnDetalhesMv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv3ActionPerformed

    private void btnDetalhesMv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv4ActionPerformed

    private void btnDetalhesMv5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv5ActionPerformed

    private void btnDetalhesMv6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesMv6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDetalhesMv6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows XP".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCartLoja;
    private javax.swing.JRadioButton btnAlugarMv1;
    private javax.swing.JRadioButton btnAlugarMv2;
    private javax.swing.JRadioButton btnAlugarMv3;
    private javax.swing.JRadioButton btnAlugarMv4;
    private javax.swing.JRadioButton btnAlugarMv5;
    private javax.swing.JRadioButton btnAlugarMv6;
    private javax.swing.JButton btnDetalhesMv1;
    private javax.swing.JButton btnDetalhesMv2;
    private javax.swing.JButton btnDetalhesMv3;
    private javax.swing.JButton btnDetalhesMv4;
    private javax.swing.JButton btnDetalhesMv5;
    private javax.swing.JButton btnDetalhesMv6;
    private javax.swing.JButton btnFinalizarLoja;
    private javax.swing.JButton btnVoltarLoja;
    private javax.swing.JLabel descMv1;
    private javax.swing.JLabel descMv2;
    private javax.swing.JLabel descMv3;
    private javax.swing.JLabel descMv4;
    private javax.swing.JLabel descMv5;
    private javax.swing.JLabel descMv6;
    private javax.swing.JLabel imgMv1;
    private javax.swing.JLabel imgMv2;
    private javax.swing.JLabel imgMv3;
    private javax.swing.JLabel imgMv4;
    private javax.swing.JLabel imgMv5;
    private javax.swing.JLabel imgMv6;
    private javax.swing.JMenuBar menuBarLoja;
    private javax.swing.JMenuItem menuFinalizarLoja;
    private javax.swing.JMenu menuLoja;
    private javax.swing.JMenuItem menuSairLoja;
    private javax.swing.JMenuItem menuVoltarLoja;
    private javax.swing.JLabel nomeMv1;
    private javax.swing.JLabel nomeMv2;
    private javax.swing.JLabel nomeMv3;
    private javax.swing.JLabel nomeMv4;
    private javax.swing.JLabel nomeMv5;
    private javax.swing.JLabel nomeMv6;
    private javax.swing.JPanel pnlFilmes;
    private javax.swing.JPanel pnlLoja;
    private javax.swing.JPanel pnlMv1;
    private javax.swing.JPanel pnlMv2;
    private javax.swing.JPanel pnlMv3;
    private javax.swing.JPanel pnlMv4;
    private javax.swing.JPanel pnlMv5;
    private javax.swing.JPanel pnlMv6;
    private javax.swing.JLabel precoMv1;
    private javax.swing.JLabel precoMv2;
    private javax.swing.JLabel precoMv3;
    private javax.swing.JLabel precoMv4;
    private javax.swing.JLabel precoMv5;
    private javax.swing.JLabel precoMv6;
    private javax.swing.JScrollPane scrollFilmes;
    private javax.swing.JScrollPane scrollJogos;
    private javax.swing.JScrollPane scrollMusica;
    private javax.swing.JPopupMenu.Separator separatorLoja;
    private javax.swing.JTabbedPane tabbedPnlLoja;
    private javax.swing.JLabel txtCartLoja;
    // End of variables declaration//GEN-END:variables
}
