/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Adm
 */
public class MainScr extends javax.swing.JFrame {

    /**
     * Creates new form MainScr
     */
    public MainScr() {
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLojaMain = new javax.swing.JButton();
        btnCliMain = new javax.swing.JButton();
        btnFuncMain = new javax.swing.JButton();
        btnSairMain = new javax.swing.JButton();
        menuBarMain = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        menuLojaMain = new javax.swing.JMenuItem();
        menuCliMain = new javax.swing.JMenuItem();
        menuFuncMain = new javax.swing.JMenuItem();
        separatorMain = new javax.swing.JPopupMenu.Separator();
        menuSairMain = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Biondi", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/boxLogoBig.png"))); // NOI18N
        jLabel1.setText("BOXBUSTER");

        btnLojaMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLojaMain.setText("Loja");
        btnLojaMain.setToolTipText("Ver produtos");
        btnLojaMain.setRequestFocusEnabled(false);
        btnLojaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLojaMainActionPerformed(evt);
            }
        });

        btnCliMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCliMain.setText("Área do cliente");
        btnCliMain.setToolTipText("Cadastrar-se ou ver seu perfil");
        btnCliMain.setRequestFocusEnabled(false);
        btnCliMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliMainActionPerformed(evt);
            }
        });

        btnFuncMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFuncMain.setText("Área do funcionário");
        btnFuncMain.setToolTipText("Ver seu perfil");
        btnFuncMain.setRequestFocusEnabled(false);

        btnSairMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSairMain.setText("Sair");
        btnSairMain.setToolTipText("Fechar programa");
        btnSairMain.setRequestFocusEnabled(false);
        btnSairMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnSairMain))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLojaMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFuncMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLojaMain)
                .addGap(18, 18, 18)
                .addComponent(btnCliMain)
                .addGap(18, 18, 18)
                .addComponent(btnFuncMain)
                .addGap(18, 18, 18)
                .addComponent(btnSairMain)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        menuMain.setText("Menu");

        menuLojaMain.setText("Loja");
        menuLojaMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLojaMainActionPerformed(evt);
            }
        });
        menuMain.add(menuLojaMain);

        menuCliMain.setText("Área do cliente");
        menuCliMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCliMainActionPerformed(evt);
            }
        });
        menuMain.add(menuCliMain);

        menuFuncMain.setText("Área do funcionário");
        menuMain.add(menuFuncMain);
        menuMain.add(separatorMain);

        menuSairMain.setText("Sair");
        menuMain.add(menuSairMain);

        menuBarMain.add(menuMain);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCliMainActionPerformed

    private void btnLojaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLojaMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLojaMainActionPerformed

    private void menuLojaMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLojaMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLojaMainActionPerformed

    private void menuCliMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCliMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCliMainActionPerformed

    private void btnSairMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows XP".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliMain;
    private javax.swing.JButton btnFuncMain;
    private javax.swing.JButton btnLojaMain;
    private javax.swing.JButton btnSairMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenuItem menuCliMain;
    private javax.swing.JMenuItem menuFuncMain;
    private javax.swing.JMenuItem menuLojaMain;
    private javax.swing.JMenu menuMain;
    private javax.swing.JMenuItem menuSairMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPopupMenu.Separator separatorMain;
    // End of variables declaration//GEN-END:variables
}
